jc/config/routes.rb
Jc::Application.routes.draw do

  resources :authors, :organizations, :author_extras, :organization_extras

  root :to => 'home#index'

  match '/author_search' => 'authors#search'
  match '/organization_search' => 'organizations#search'
end

jc/app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name
  has_one :author_extra
  belongs_to :organization
  has_many :report_authors
  has_many :reports, :through => :report_authors
end

jc/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @author }
    end
  end

  # GET /authors/search/xx
  def search
    @author = Author.where("name = ?", params[:name]).first
    puts params[:name]
    respond_to do |format|
      format.html # search.html.erb
      format.json { render :json => @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, :notice => 'Author was successfully created.' }
        format.json { render :json => @author, :status => :created, :location => @author }
      else
        format.html { render :action => "new" }
        format.json { render :json => @author.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, :notice => 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @author.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

jc/app/helpers/authors_helper.rb
module AuthorsHelper
end

jc/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jc/app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

jc/app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Organization</th>
    <th>ReportCount</th>
    <th>ReportCorrectnessCount</th>
  </tr>
  
<%= will_paginate @authors %>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= author.organization.name %></td>
    <td><%= author.reports.size %>
    <% correctness_count = 0
        author.reports.each do |report|
            correctness_count += report.report_extra.right
        end
    %>
    <td><%= correctness_count %>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

jc/app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

jc/app/views/authors/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>
<table border="1">
  <tr>
      <td>report title</td>
      <td>correctness</td>
  </tr>

<% @author.reports.each do |report| %>
  <tr>
      <td><%= report.report_title %></td>
      <td><%= report.report_extra.right %></td>
  </tr>
<% end %>

</table>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

jc/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>
<table border="1">
  <tr>
      <th>Report Title</th>
      <th>Correctness</th>
  </tr>

<% @author.reports.each do |report| %>
  <tr>
      <td><%= report.report_title %></td>
      <td><%= report.report_extra.right %></td>
  </tr>
<% end %>

</table>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>