jc/config/routes.rb
Jc::Application.routes.draw do

  resources :authors, :organizations, :author_extras, :organization_extras

  root :to => 'home#index'

  match '/author_search' => 'authors#search'
  match '/organization_search' => 'organizations#search'
end

jc/app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name
  has_one :organization_extra
  has_many :authors
  has_many :report_organizations
  has_many :reports, :through => :report_organizations
end

jc/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @organization }
    end
  end

  # GET /authors/search/xx
  def search
    @organization = Organization.where("name = ?", params[:name]).first
    # respond_to do |format|
    #   format.html # search.html.erb
    #   format.json { render :json => @organizations }
    # end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, :notice => 'Organization was successfully created.' }
        format.json { render :json => @organization, :status => :created, :location => @organization }
      else
        format.html { render :action => "new" }
        format.json { render :json => @organization.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, :notice => 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @organization.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

jc/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

jc/app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jc/app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

jc/app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.name %></td>
    <td><%= organization.authors.first.name %></td>
    <td><%= link_to 'Show', organization %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td><%= link_to 'Destroy', organization, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organization', new_organization_path %>

jc/app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

jc/app/views/organizations/search.html.erb
<p id="notice"><%= notice %></p>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Organization</th>
    <th>Report Count</th>
    <th>Report Correctness Count</th>
    <th>Report Correctness Ratio</th>
    <th>More...</th>
  </tr>

<% @organization.authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= @organization.name %></td>
    <% if author.author_extra == nil %>
    <td></td><td></td><td></td>
    <% else %>
    <td><%= author.author_extra.report_count %></td>
    <td><%= author.author_extra.report_correctness_count %></td>
    <td><%= author.author_extra.report_correctness_ratio %></td>
    <% end %>
    <td><%= link_to 'Show Reports', author %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

jc/app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>