jc/config/routes.rb
Jc::Application.routes.draw do

  resources :authors, :organizations, :author_extras, :organization_extras

  root :to => 'home#index'

  match '/author_search' => 'authors#search'
  match '/organization_search' => 'organizations#search'
end

jc/app/models/organization_extra.rb
class OrganizationExtra < ActiveRecord::Base
  belongs_to :organization
  attr_accessible :report_correctness_count, :report_correctness_ratio, :report_count
end

jc/app/controllers/organization_extras_controller.rb
class OrganizationExtrasController < ApplicationController
  # GET /organization_extras
  # GET /organization_extras.json
  def index
    @organization_extras = OrganizationExtra.order("report_correctness_ratio DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @organization_extras }
    end
  end

  # GET /organization_extras/1
  # GET /organization_extras/1.json
  def show
    @organization_extra = OrganizationExtra.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @organization_extra }
    end
  end

  # GET /organization_extras/new
  # GET /organization_extras/new.json
  def new
    @organization_extra = OrganizationExtra.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @organization_extra }
    end
  end

  # GET /organization_extras/1/edit
  def edit
    @organization_extra = OrganizationExtra.find(params[:id])
  end

  # POST /organization_extras
  # POST /organization_extras.json
  def create
    @organization_extra = OrganizationExtra.new(params[:organization_extra])

    respond_to do |format|
      if @organization_extra.save
        format.html { redirect_to @organization_extra, :notice => 'Organization extra was successfully created.' }
        format.json { render :json => @organization_extra, :status => :created, :location => @organization_extra }
      else
        format.html { render :action => "new" }
        format.json { render :json => @organization_extra.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /organization_extras/1
  # PUT /organization_extras/1.json
  def update
    @organization_extra = OrganizationExtra.find(params[:id])

    respond_to do |format|
      if @organization_extra.update_attributes(params[:organization_extra])
        format.html { redirect_to @organization_extra, :notice => 'Organization extra was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @organization_extra.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /organization_extras/1
  # DELETE /organization_extras/1.json
  def destroy
    @organization_extra = OrganizationExtra.find(params[:id])
    @organization_extra.destroy

    respond_to do |format|
      format.html { redirect_to organization_extras_url }
      format.json { head :no_content }
    end
  end
end

jc/app/helpers/organization_extras_helper.rb
module OrganizationExtrasHelper
end

jc/app/views/organization_extras/_form.html.erb
<%= form_for(@organization_extra) do |f| %>
  <% if @organization_extra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization_extra.errors.count, "error") %> prohibited this organization_extra from being saved:</h2>

      <ul>
      <% @organization_extra.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jc/app/views/organization_extras/edit.html.erb
<h1>Editing organization_extra</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization_extra %> |
<%= link_to 'Back', organization_extras_path %>

jc/app/views/organization_extras/index.html.erb
<h1>Listing organization_extras</h1>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Author Count</th>
    <th>Report Count</th>
    <th>Report Correctness Count</th>
    <th>Report Correctness Ratio</th>
    <th>More ...</th>
  </tr>

<% @organization_extras.each do |organization_extra| %>
  <tr>
    <td><%= organization_extra.organization.name %></td>
    <td><%= organization_extra.organization.authors.size %></td>
    <td><%= organization_extra.report_count %></td>
    <td><%= organization_extra.report_correctness_count %></td>
    <td><%= organization_extra.report_correctness_ratio * 100 %>%</td>
    <td><%= link_to 'Show Author', organization_extra.organization %></td>
  </tr>

<% end %>
</table>

<br />

<%= link_to 'New Organization extra', new_organization_extra_path %>

jc/app/views/organization_extras/new.html.erb
<h1>New organization_extra</h1>

<%= render 'form' %>

<%= link_to 'Back', organization_extras_path %>

jc/app/views/organization_extras/show.html.erb
<p id="notice"><%= notice %></p>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Organization</th>
    <th>Report Count</th>
    <th>Report Correctness Count</th>
    <th>Report Correctness Ratio</th>
    <th>More...</th>
  </tr>

<% @organization.authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= @organization.name %></td>
    <% if author.author_extra == nil %>
    <td></td><td></td><td></td>
    <% else %>
    <td><%= author.author_extra.report_count %></td>
    <td><%= author.author_extra.report_correctness_count %></td>
    <td><%= author.author_extra.report_correctness_ratio %></td>
    <% end %>
    <td><%= link_to 'Show Reports', author %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>