jc/config/routes.rb
Jc::Application.routes.draw do

  resources :authors, :organizations, :author_extras, :organization_extras

  root :to => 'home#index'

  match '/author_search' => 'authors#search'
  match '/organization_search' => 'organizations#search'
end

jc/app/models/author_extra.rb
class AuthorExtra < ActiveRecord::Base
  belongs_to :author
  attr_accessible :report_correctness_count, :report_count, :report_correctness_ratio
end

jc/app/controllers/author_extras_controller.rb
class AuthorExtrasController < ApplicationController
  # GET /author_extras
  # GET /author_extras.json
  def index
    @author_extras = AuthorExtra.order("report_correctness_ratio DESC").paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @author_extras }
    end
  end

  # GET /author_extras/1
  # GET /author_extras/1.json
  def show
    @author_extra = AuthorExtra.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @author_extra }
    end
  end

  # GET /author_extras/new
  # GET /author_extras/new.json
  def new
    @author_extra = AuthorExtra.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @author_extra }
    end
  end

  # GET /author_extras/1/edit
  def edit
    @author_extra = AuthorExtra.find(params[:id])
  end

  # POST /author_extras
  # POST /author_extras.json
  def create
    @author_extra = AuthorExtra.new(params[:author_extra])

    respond_to do |format|
      if @author_extra.save
        format.html { redirect_to @author_extra, :notice => 'Author extra was successfully created.' }
        format.json { render :json => @author_extra, :status => :created, :location => @author_extra }
      else
        format.html { render :action => "new" }
        format.json { render :json => @author_extra.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /author_extras/1
  # PUT /author_extras/1.json
  def update
    @author_extra = AuthorExtra.find(params[:id])

    respond_to do |format|
      if @author_extra.update_attributes(params[:author_extra])
        format.html { redirect_to @author_extra, :notice => 'Author extra was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @author_extra.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /author_extras/1
  # DELETE /author_extras/1.json
  def destroy
    @author_extra = AuthorExtra.find(params[:id])
    @author_extra.destroy

    respond_to do |format|
      format.html { redirect_to author_extras_url }
      format.json { head :no_content }
    end
  end
end

jc/app/helpers/author_extras_helper.rb
module AuthorExtrasHelper
end

jc/app/views/author_extras/_form.html.erb
<%= form_for(@author_extra) do |f| %>
  <% if @author_extra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author_extra.errors.count, "error") %> prohibited this author_extra from being saved:</h2>

      <ul>
      <% @author_extra.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jc/app/views/author_extras/edit.html.erb
<h1>Editing author_extra</h1>

<%= render 'form' %>

<%= link_to 'Show', @author_extra %> |
<%= link_to 'Back', author_extras_path %>

jc/app/views/author_extras/index.html.erb
<h1>Listing author_extras</h1>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Organization</th>
    <th>Report Count</th>
    <th>Report Correctness Count</th>
    <th>Report Correctness Ratio</th>
    <th>More...</th>
  </tr>

<%= will_paginate @author_extras %>

<% @author_extras.each do |author_extra| %>
  <tr>
    <td><%= author_extra.author.name %></td>
    <td><%= author_extra.author.organization.name %></td>
    <td><%= author_extra.report_count %></td>
    <td><%= author_extra.report_correctness_count %></td>
    <td><%= author_extra.report_correctness_ratio * 100 %>%</td>
    <td><%= link_to 'Show Reports', author_extra.author %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author extra', new_author_extra_path %>

jc/app/views/author_extras/new.html.erb
<h1>New author_extra</h1>

<%= render 'form' %>

<%= link_to 'Back', author_extras_path %>

jc/app/views/author_extras/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_author_extra_path(@author_extra) %> |
<%= link_to 'Back', author_extras_path %>